// Generated by Selenium IDE

import model.ContactData;
import model.GroupData;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import tests.TestBase;
public class CreationContactTests extends TestBase {

  @Test
  public void canCreatedContact() {
    TestBase.app.contact().createdContact(new ContactData());
  }


}
